FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["Ventas.Api/Ventas.Api.csproj", "Ventas.Api/"]
COPY ["Ventas.Domain/Ventas.Domain.csproj", "Ventas.Domain/"]
RUN dotnet restore "Ventas.Api/Ventas.Api.csproj"
COPY . .
WORKDIR "/src/Ventas.Api"
RUN dotnet build "Ventas.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Ventas.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Ventas.Api.dll"]
