// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ventas.Domain.Data;

#nullable disable

namespace Ventas.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927154341_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ventas.Domain.Entities.CajaTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("MontoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CajasTurnos");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "BODYS MANGA CERO"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "BODYS MANGA CORTA"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "BODYS MANGA LARGA"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "POLOS"
                        });
                });

            modelBuilder.Entity("Ventas.Domain.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDocenas")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoHistoricoPorDocena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioPorDocena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVentas");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.InventarioSucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDocenas")
                        .HasColumnType("int");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.HasIndex("SucursalId");

                    b.ToTable("InventariosSucursal");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoQR")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("CostoPorDocena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EtiquetasPendientes")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreCorto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecioPorDocena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Nombre");

                    b.ToTable("Modelos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 4,
                            CodigoQR = "",
                            CostoPorDocena = 0m,
                            EtiquetasPendientes = 0,
                            Nombre = "Polo Manga Corta Cuello Cuadrado",
                            PrecioPorDocena = 10.00m,
                            Talla = "Estándar"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            CodigoQR = "",
                            CostoPorDocena = 0m,
                            EtiquetasPendientes = 0,
                            Nombre = "Body Manga Corta Cuello Cuadrado",
                            PrecioPorDocena = 14.00m,
                            Talla = "Estándar"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            CodigoQR = "",
                            CostoPorDocena = 0m,
                            EtiquetasPendientes = 0,
                            Nombre = "Body Manga Corta Espalda Descubierta",
                            PrecioPorDocena = 12.50m,
                            Talla = "Estándar"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            CodigoQR = "",
                            CostoPorDocena = 0m,
                            EtiquetasPendientes = 0,
                            Nombre = "Body Manga Larga Cuello Cuadrado",
                            PrecioPorDocena = 14.00m,
                            Talla = "Estándar"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            CodigoQR = "",
                            CostoPorDocena = 0m,
                            EtiquetasPendientes = 0,
                            Nombre = "Body Manga Cero Escote Espejo",
                            PrecioPorDocena = 10.50m,
                            Talla = "Estándar"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 4,
                            CodigoQR = "",
                            CostoPorDocena = 0m,
                            EtiquetasPendientes = 0,
                            Nombre = "Polo Manga Corta Cuello Corazón",
                            PrecioPorDocena = 10.00m,
                            Talla = "Estándar"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 1,
                            CodigoQR = "",
                            CostoPorDocena = 0m,
                            EtiquetasPendientes = 0,
                            Nombre = "Body Manga Cero Tirita",
                            PrecioPorDocena = 10.00m,
                            Talla = "Estándar"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 4,
                            CodigoQR = "",
                            CostoPorDocena = 0m,
                            EtiquetasPendientes = 0,
                            Nombre = "Polo Lazo",
                            PrecioPorDocena = 11.50m,
                            Talla = "Estándar"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 4,
                            CodigoQR = "",
                            CostoPorDocena = 0m,
                            EtiquetasPendientes = 0,
                            Nombre = "Polo Manga Corta Cuello Redondo",
                            PrecioPorDocena = 9.50m,
                            Talla = "Estándar"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 2,
                            CodigoQR = "",
                            CostoPorDocena = 0m,
                            EtiquetasPendientes = 0,
                            Nombre = "Body Manga Corta Cuello Corazón",
                            PrecioPorDocena = 12.50m,
                            Talla = "Estándar"
                        });
                });

            modelBuilder.Entity("Ventas.Domain.Entities.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDocenas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Lima",
                            Nombre = "Sede Principal"
                        });
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IntentosFallidos = 0,
                            PasswordHash = "$2a$11$PxJVDpSwx9mjYGSxORIPeOl2VP5kIf/CLkkNOeSBLFF0FtxRP28om",
                            Rol = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaTurnoId")
                        .HasColumnType("int");

                    b.Property<string>("ClienteDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Correlativo")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Serie")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<string>("TipoComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CajaTurnoId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.CajaTurno", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.DetalleVenta", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modelo");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.InventarioSucursal", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.Modelo", "Modelo")
                        .WithMany("Inventarios")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Inventarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modelo");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Modelo", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Modelos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.MovimientoInventario", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modelo");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Venta", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.CajaTurno", "CajaTurno")
                        .WithMany("Ventas")
                        .HasForeignKey("CajaTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CajaTurno");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.CajaTurno", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Modelo", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Sucursal", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}

